pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/aiyza-junaid/lab_Task10_11.git'
            }
        }

        stage('Dependency Installation') {
            steps {
                bat 'npm install' 
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t your-image-name .'
            }
        }

        stage('Run Docker Image') {
            steps {
                bat 'docker run -d -p 3000:11 your-image-name'
            }
        }

       
        }
    }
}
